-- ElectricSQL extension and RLS setup migration
-- Generated by Claudia Phase 0b

-- Install required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "electric";

-- Enable Row-Level Security on core tables
ALTER TABLE "users"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "agents"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memory"   ENABLE ROW LEVEL SECURITY;

-- NOTE: Specific RLS policies will be added in a later migration once
-- the authentication model is finalised. This just turns RLS on so
-- that policies can be attached incrementally.